version: '3.4'
# volumes:
#   node_modules:
networks:
  mojaloop-net:
    name: mojaloop-net

services:

  # non-server running container to launch tests from
  scheme-adapter-int:
    networks:
      - mojaloop-net
    container_name: scheme-adapter-int
    build:
      context: .
      dockerfile: Dockerfile-integration
      target: builder
    env_file: ./src/test/config/integration.env
    volumes:
    #   # - ./src/test:/src/test
      - ./src:/src
    #   - node_modules:/src/node_modules
    depends_on:
      - redis
    command:
      - 'tail -f /dev/null'
    entrypoint:
      - sh
      - -c
